import "./globals.css";
import Navbar from "./navbar";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		// old background color -> (#f2f2f2)
		<html className='bg-[#f2f2f2]' lang='en'>
			<body>
				<Navbar />
				{children}
				{/* Temp Footer below */}
				<div className='my-48'></div>
			</body>
		</html>
	);
}
